# MkDocs config for Backstage TechDocs.
# Edit at will — Backstage rebuilds on next view.
# https://backstage.io/docs/features/techdocs/getting-started

site_name: xdg-desktop-portal-cosmic
site_description: xdg-desktop-portal-cosmic

docs_dir: docs

plugins:
  - techdocs-core
